### ISSUE TITLE
🚩 Improve Matrix compatibility

### ISSUE THREAD

**Issue by lindseydiloreto** [doublesecretagency/craft-googlemaps#1]
At launch, the Google Maps plugin will have partial (read: buggy) support for Address-in-Matrix fields.

This is obviously a critical component, so completing this feature is our highest priority.

**Comment by zizther** [comment]
Look forward to moving to this plugin once this issue is sorted, as the project in mind has this requirement.

**Comment by damienbuckley** [comment]
Any progress with this? Address field works fine in an entry but doesn't show up at all in a matrix block.

**Comment by lindseydiloreto** [comment]
@damienbuckley Still extremely high on our radar. Sorry for the delay.

Our realistic ETA is about 7 - 10 days from now. If you haven't heard from me by then, feel free to check back. 👍

**Comment by damienbuckley** [comment]
Great stuff!

**Comment by darinlarimore** [comment]
I believe I'm experiencing this issue too. 
I'm able to pull the data from the address fields but they do not show when editing the entry like your encounter @damienbuckley.
Also possibly related, I receive this TypeError when attempting to edit the field here `admin/settings/fields`


>TypeError
 Argument 1 passed to craft\services\Fields::getGroupById() must be of the type int, null given, called in .../vendor/craftcms/cms/src/base/Field.php on line 565

**Comment by lindseydiloreto** [comment]
Good news everyone, this is done! 🎉

As of **v4.0.4**, the Google Maps plugin is now fully compatible with Matrix, Neo, and Super Table.

**Comment by lindseydiloreto** [comment]
@darinlarimore Try updating to the latest and give it another shot. If you're still seeing issues after that, feel free to DM me or start a new thread. 👍

**Comment by lindseydiloreto** [comment]
Just FYI, I've added a new page to the docs on how to use an [Address in a Matrix Field](https://plugins.doublesecretagency.com/google-maps/guides/address-in-a-matrix-field/).

**Comment by darinlarimore** [comment]
Thank you! I can confirm this is working for me now! @lindseydiloreto

**Comment by lindseydiloreto** [comment]
Excellent, thanks for the update @darinlarimore!
