### ISSUE TITLE
Initial Craft 5 Support

### ISSUE THREAD

**Issue by kylecotter** [doublesecretagency/craft-googlemaps#105]
Not sure what your plans are for Craft 5, but when sideloading the plugin the only adjustments seemingly needed to keep things functioning is updating the Craft requirement to the 5.0 beta [here](https://github.com/doublesecretagency/craft-googlemaps/blob/0f92df80ea212afe2e642dd688fec2477b47fe87/composer.json#L34) and renaming `craft\services\Utilities::EVENT_REGISTER_UTILITY_TYPES` to `EVENT_REGISTER_UTILITIES` [here](https://github.com/doublesecretagency/craft-googlemaps/blob/0f92df80ea212afe2e642dd688fec2477b47fe87/src/GoogleMapsPlugin.php#L209).

Think it's possible to get some type of dev branch/version going?

Thanks!

**Comment by lindseydiloreto** [comment]
Hi @kylecotter, thanks for asking!

Full support for Craft 5 is **100% on the way**. Now that the C5 beta has officially dropped, I plan on having all of our plugins updated by this time next week.

Thanks for the pointers! I'll make sure both of those issues are addressed when updating the Google Maps plugin. 👍 

Will keep this thread open until Google Maps for Craft 5 ships.

**Comment by lindseydiloreto** [comment]
Good news, support for Craft 5 is now available in [v5.0.0-beta.1](https://github.com/doublesecretagency/craft-googlemaps/releases/tag/5.0.0-beta.1). 🎉 

It seems pretty stable so far, but of course let me know if you find any bugs!

**Comment by lindseydiloreto** [comment]
Quick update, the Google Maps plugin is now [out of beta](https://github.com/doublesecretagency/craft-googlemaps/releases/tag/5.0.0) for Craft 5.  ✅
