### ISSUE TITLE
Allow different Addresses per different Sites

### ISSUE THREAD

**Issue by lindseydiloreto** [doublesecretagency/craft-googlemaps#11]
The Address field should be aware of which Site is being edited. Currently, all Sites share the same Address data.

I believe it's mostly a matter of adding a `siteId` column to the Address table in the database. We'll find out how true that is once I dive into the task.

This feature is expected to be released as early as **v4.1**, or as late as **v4.3**. If anything changes, I'll post back to this thread!

---

> Migrated from Smart Map: https://github.com/doublesecretagency/craft-smartmap/issues/22

**Comment by AndrewMac** [comment]
Hi Lindsey, good to see you've still got this on the roadmap! I remember we discussed this a while back, when the plugin was still SmartMap. We really need this feature as our sites are mainly English/Thai, and Thai has its own script. The same issue would, of course, come up with China, Japan, the Middle East nations and a host of others.

For example, with the location "Chiang Mai, Thailand"
The Thai is เชียงใหม่ ประเทศไทย

Although the location data can be looked up in English, we use the Google Maps address fields (along with some custom fields) to populate the marker popup and the entry page. So we really need the Thai version if possible :-)

Thanks so much for considering this, Andrew

**Comment by lindseydiloreto** [comment]
Certainly, no problem! I still regard it as one of the more important issues. 🙂

Once some of the 4.1 issues are resolved, I look forward to knocking this out in 4.2.

**Comment by idawgik** [comment]
I have a project I'm currently working on that could really use this feature. In our case, it's a multi-site where we have location data for each site in a global. Since I can't set the address field as translateable, the location info is shared between both sites (even though they have separate addresses). I would need to look at setting things up differently to make it work as things are now, so getting this support would be a huge plus.

**Comment by MoritzLost** [comment]
@lindseydiloreto Hey Lindsey, any updates on supporting translation methods / multi-site support? This might become very relevant to an upcoming project. Is this still planned, and if so, is there any kind of ETA you can share?

**Comment by svondervoort** [comment]
Any update on this? Currently running into the same issue with a multisite and an address field in globals.

**Comment by lindseydiloreto** [comment]
I believe I _finally_ have this done... Would anyone on this thread care to pull the latest dev version and test it?

```js
"doublesecretagency/craft-googlemaps": "dev-v4-dev"
```

This is currently only available on **Craft 4**. Once it is deemed stable, it will be ported to Craft 5.

⚠️  Please make sure to backup your database first, as this update will run a significant migration!

---

## Multisite Support

This update formally introduces [multisite support](https://plugins.doublesecretagency.com/google-maps/address-field/multisite-support/). In other words, an Address can now contain **different values** for each site in your project.

All standard translation methods are supported.

---

Once this feature is confirmed to be working and stable on Craft 4, I will tag and release a Google Maps update.

Additionally, I will also port this feature to:

- Google Maps for Craft 5
- Mapbox for Craft 4
- Mapbox for Craft 5

For anyone willing to take it for spin, please let me know once you've run some tests. I'm eager to hear how it goes! 🙏

**Comment by AndrewMac** [comment]
Hi @lindseydiloreto, that’s great news! Sadly, though, I'm not currently running any Craft 4 sites, and I'm not sure when I might have time to spin one up for testing. I'll try to do that, but with any luck, some of the others will be in a better position than I am.

**Comment by svondervoort** [comment]
That's great, I have some development research time Friday next week where I can give it a test.

**Comment by MoritzLost** [comment]
@lindseydiloreto Just gave this a try, looks good to me 👍 

Added a small cosmetic comment here, but everything seems to be working: https://github.com/doublesecretagency/craft-googlemaps/commit/c0db6434645fae967439c81a987888e9e39da989#r142853593

One thing to note is that this will multiply the number of rows in the database with the number of sites. As I mentioned on Discord, I think this is the best way, just something to note. Probably useful to mention this in the docs or changelog. Might have performance and storage space implications for sites with tons of addresses and sites.

_In theory_, it might be possible to leave the site ID empty if the field is set to not be translatable and only save the address once in this case. However, I'm not sure if this will work with the way the address table is joined in `modifyElementsQuery`. Probably safest not to touch this and just always set the site ID, even if it means duplicating some rows unnecessarily.

**Comment by lindseydiloreto** [comment]
@MoritzLost Ok great, thanks for testing everything! 🙏 

I agree that this table structure (a row for each site) is probably the best approach. It seems to work well with how Craft handles things internally, and is hopefully somewhat future-proof.

Per your advice, I just added a migration warning to both the [CHANGELOG](https://github.com/doublesecretagency/craft-googlemaps/blob/d93502a903c851503eb777bc6a378843f5a93f2c/CHANGELOG.md#changelog) and the [docs](https://plugins.doublesecretagency.com/google-maps/address-field/multisite-support/#multisite-migration).

Thanks for looking over everything, it's greatly appreciated! 🍺

**Comment by lindseydiloreto** [comment]
Took a bit longer than I thought, but multisite support is now available in Craft 5... 👍 

```js
"doublesecretagency/craft-googlemaps": "dev-v5-dev"
```

It ended up being more than a simple copy & paste from the Craft 4 version. I ultimately had to rewrite a significant portion of the migration for Craft 5, since the `content` has become a JSON column in the `element_sites` table.

I'm not sure which of you are running Google Maps on a Craft 5 website (@AndrewMac?), but I would love to confirm that this works before going live with it. I'm now about 95% confident that everything works as desired, so please take it for a test drive when you get a chance.

Thanks everyone! Looking forward to officially releasing this once we've confirmed it works for Craft 5!

**Comment by AndrewMac** [comment]
Hi @lindseydiloreto, and thanks so much for continuing to work on this. I finally got time to update a local site with your new dev version, but the first thing I noticed is that after the migration the field data for all entries is now blank for both the original and the second-language site. So, unless that's caused by something at my end, it might not be ready for release quite yet ;-)

**Comment by lindseydiloreto** [comment]
Got it, thanks for reporting back @AndrewMac! I think I might know what's going on there, I'll try to sort it out shortly.

Thanks for the testing and feedback! 🙏

**Comment by lindseydiloreto** [comment]
@AndrewMac After you ran the migration, did you notice the following changes in the database?
- Was the `siteId` column added to the `googlemaps_addresses` table?
- Did the `googlemaps_addresses` table become populated with a ton of new (duplicated) data for each site? The new data should roughly amount to **the number of stored Addresses you had** multiplied by **the number of sites you have**.

Let me know if at least those changes were successful. That is the core of the migration, which largely carried over from the Craft 4 implementation. Some additional steps are required in Craft 5.

**Comment by lindseydiloreto** [comment]
@AndrewMac I wasn't able to completely reproduce your issue, but I did iron out some other minor wrinkles.

Would you mind giving it another shot when you get a chance?

```js
"doublesecretagency/craft-googlemaps": "dev-v5-dev"
```

**Comment by lindseydiloreto** [comment]
🎉  **Great news!!** Multisite support is now [officially available](https://plugins.doublesecretagency.com/google-maps/address-field/multisite-support/) for both Craft 4 ([v4.6.0](https://github.com/doublesecretagency/craft-googlemaps/releases/tag/4.6.0)) and Craft 5 ([v5.1.0](https://github.com/doublesecretagency/craft-googlemaps/releases/tag/5.1.0))!

I tried to be extremely thorough, so hopefully there are no bugs to be found. But if anyone stumbles across an issue, please start a new thread and we can handle it over there.

Thanks for everyone's infinite patience in getting this feature out the door! 🙏
