### ISSUE TITLE
Plugin doesnt work in Craft cms v4.9.5

### ISSUE THREAD

**Issue by mufi-siebird** [doublesecretagency/craft-googlemaps#111]
There is this updates craft cms made:

Scalar element queries now set $select to the scalar expression, and $orderBy, $limit, and $offset to null, on the element query. ([#15001](https://github.com/craftcms/cms/issues/15001))
...

I guess because of that, plugin throws order by distance error and not loads the data.

Error I recieve is:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'distance' in 'having clause'

Query:
```
{% set query = craft.entries.section("mapsection").mapAddress(params).limit(limit) %}
{% if pagination %}
    {% paginate query as pageInfo, entries %}
{% else %}
    {% set entries = query.all() %}
{% endif %}
```

**Comment by nickdenys** [comment]
We're also having this issue with the exact same error.

Craft CMS version: 4.9.5
Plugin version: 4.5.2

**Comment by mufi-siebird** [comment]
> We're also having this issue with the exact same error.
> 
> Craft CMS version: 4.9.5 Plugin version: 4.5.2

I solved it by downgrading craft cms to 4.9.4 for now.

**Comment by nickdenys** [comment]
@mufi-siebird Cheers, that made it work again 👍

**Comment by lindseydiloreto** [comment]
Thank you both for reporting it. We'll take a look shortly to see if the fix should be on our side, or within Craft core (since that's what changed).

**Comment by elivz** [comment]
I'm seeing this as well. Have downgraded to 4.9.4 for the moment, but following here for a permanent fix.

**Comment by brandonkelly** [comment]
Craft 4.10.2 and 5.2.2 are out with a fix for this.

**Comment by lindseydiloreto** [comment]
Brilliant, thanks @brandonkelly! 🙏 🎉
