### ISSUE TITLE
Address Field setting all locations to Bermuda

### ISSUE THREAD

**Issue by CreateSean** [doublesecretagency/craft-googlemaps#123]
Craft 5.3.6
Maps 5.0.2

If the GPS coordinates are already there (imported via feedme) the map has the correct location. However if later you manually update via the address the map sets to bermuda.

![image](https://github.com/user-attachments/assets/ee802ce2-89bc-46b1-8398-307a48dfab69)

**Comment by lindseydiloreto** [comment]
I think you're more or less experiencing normal behavior. If an Address does not have coordinates (which this one does not), it is natural for the plugin to show you a map of the Bermuda Triangle as an indication that the coordinates are invalid.

https://plugins.doublesecretagency.com/google-maps/guides/bermuda-triangle/

Per our private conversation, you might be running into an issue that is not actually a bug. I'll follow up via DM to sort it out.
