### ISSUE TITLE
Huge controls in Address field map

### ISSUE THREAD

**Issue by carlcs** [doublesecretagency/craft-googlemaps#19]
The controls in an Address field map are huge compared to the rest of the control panel UI. Can you please look into reducing the size using the `controlSize` option?

https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.controlSize

**Comment by lindseydiloreto** [comment]
Ah, good call! I didn't even realize that was possible.

I'll add this when I also add the [language control](https://github.com/doublesecretagency/craft-googlemaps/pull/18#issuecomment-799623188) to the Address field settings.

**Comment by carlcs** [comment]
Thanks Lindsey, I’m looking forward to that release! ☺️

**Comment by lindseydiloreto** [comment]
Good news, this has been added in [v4.0.5](https://github.com/doublesecretagency/craft-googlemaps/releases/tag/4.0.5)! 🎉

I also set a more reasonable default value for the control size. Thanks for letting me know this was possible!
