### ISSUE TITLE
Complete GraphQL compatibility

### ISSUE THREAD

**Issue by lindseydiloreto** [doublesecretagency/craft-googlemaps#2]
The plugin currently provides no support for GraphQL. Demand for compatibility is relatively high.

We intend to add GraphQL compatibility by the **4.1** (or at the latest, 4.2) version release.

**Comment by lindseydiloreto** [comment]
See original related Smart Map issues:

 - https://github.com/doublesecretagency/craft-smartmap/issues/58
 - https://github.com/doublesecretagency/craft-smartmap/issues/59

**Comment by Saboteur777** [comment]
When may we expect this to be released?

**Comment by lindseydiloreto** [comment]
Short answer, probably about 2 months from now.

Longer answer, it's the central feature of the [4.1.0 roadmap](https://github.com/doublesecretagency/craft-googlemaps/milestone/1). Also worth noting that there are a couple remaining items on the [4.0.x roadmap](https://github.com/doublesecretagency/craft-googlemaps/milestone/2), though those issues are minor and straightforward.

I also have a couple of near-term hurdles IRL, like moving to a new house and taking a planned vacation. I'd certainly like to push GraphQL compatibility out much sooner, but 2 months is actually a realistic timeline.

Hope that helps! 🙂

**Comment by Saboteur777** [comment]
Thanks for your answer and your estimation, Lindsey! This helped me telling the client when they may expect my related task to be ready. 

p.s.: have a nice vacation and enjoy your new home! :)

**Comment by lindseydiloreto** [comment]
Vacation was great, and the new home is lovely, thanks! 😄 

Just a heads up... something has come up which is going to push this timeline back another 2-3 months.

It is still very much our [top priority](https://github.com/doublesecretagency/craft-googlemaps/milestone/1) in terms of the Google Maps plugin, so I can assure you that we will be addressing it as soon as possible.

**Comment by Saboteur777** [comment]
Thanks for the heads up!

**Comment by michaelfromtheoutfit** [comment]
Hey @lindseydiloreto! Would love to see this feature as well. We have a few clients that have a significant amount of locations and being able to use GraphQL to sync that data from their SAP would be a game changer. Thanks for the awesome plugin!

**Comment by lindseydiloreto** [comment]
Thanks @michaelfromtheoutfit! Perfect timing then, I'm just getting ready to (finally) implement GraphQL.

I want to do a deep dive to make sure that the implementation is thorough and comprehensive. There's a fair amount of ground to cover, I want to take my time and do it right.

With any luck, I'll have something up within about 4 weeks (but no promises). 🤞

**Comment by michaelfromtheoutfit** [comment]
That's fantastic news @lindseydiloreto! If you need anyone to help with testing and/or to run any ideas by, please feel free to hit me up.

**Comment by lindseydiloreto** [comment]
Hello extremely patient friends,

After carefully deliberating on this for the last several weeks, we have made the difficult business decision to **pause development of GraphQL support for the moment**. I apologize for any inconvenience, we will resume working on it as soon as the Craft 4 beta is released.

It was announced a few weeks ago at this year's Dot All conference that a core Address field will be introduced in Craft 4. The details are still very fuzzy, but we will strive to make our 3rd-party Address field nearly interchangeable with the native 1st-party Address field.

With this in mind, the 1st-party field will clearly support some level of GraphQL. We do not want to "reinvent the wheel" before the wheel has even been invented. Once the Craft 4 beta is publicly available, we will be adapting to the same GraphQL standards laid out by the native 1st-party Address field.

I know this may be frustrating for some folks, and again I apologize. The announcement at Dot All surprised us as well. We still view GraphQL support as a highly important feature, and look forward to developing it as soon as the Craft 4 beta is available (currently scheduled for Q1 of 2022).

In the meantime, if you face some level of urgency supporting GraphQL with the _current_ version of our 3rd-party Address field, please reach out to me on Discord. I'm happy to help you build a module which will close the gap between what you need, and what the plugin currently offers.

Thanks for your understanding! We'll obviously keep this thread open until proper GraphQL support is in place. 🙏

**Comment by lindseydiloreto** [comment]
Good news!! (albeit much, much, much later than anyone expected)

**GraphQL is now supported in the Google Maps plugin for Craft CMS.** 🎈 

This was added as part of the recent [v4.3 release](https://www.doublesecretagency.com/blog/google-maps-plugin-v4-3). It has by far been one of our oldest and most popular feature requests, making it a huge relief to now have some level of GraphQL support. Thanks to everyone who has been patiently waiting for this day.

It's worth noting that "complete" GraphQL support was a far more ambitious goal than I initially realized. Implementing [read & write capabilities](https://plugins.doublesecretagency.com/google-maps/address-field/graphql/) for an Address field came with a series of challenges and a steep learning curve. However, we see it as only the beginning of what is now possible using GraphQL with the Google Maps plugin.

I'll be opening up a new Github ticket to cover any GraphQL items which haven't yet been implemented. This includes, but may not be limited to...

- Proximity Searches
- Address Geocoding Lookups
- Visitor Geolocation (if possible)

For all future GraphQL feedback, we can move the discussion over to the new thread.

Thanks again everyone, and sorry for the many-years delay bringing this to fruition! 🙃
