### ISSUE TITLE
Unable to install 4.0.8 from SmartMap

### ISSUE THREAD

**Issue by darylknight** [doublesecretagency/craft-googlemaps#28]
Thanks for looking into the null field issue and releasing a fix! I'm trying to update the same site as last week, and instead of it installing and being unable to access the Fields section afterwards, I now can't install Google Maps at all. Here's what happens:

- Making sure the database is running Smart Map, with no PC or database changes
- Try to install Google Maps through the control panel
- Composer starts running in the control panel and says it was successful
- Google Maps is still missing
- Smart Map is still installed
- An empty table is created in the database called `googlemaps_addresses`

Sending you the web.log file via Discord!

PHP 8.0.2
Craft CMS 3.6.13 (also tried wit 3.6.12.1 )
Smart Map 3.3.5
Google Maps 4.0.8

**Comment by cgooderham94** [comment]
I've also experienced the same issue with 4.0.8. I had to delete the `googlemaps_addresses` table from the DB and downgrade 4.0.7, which seems to work fine.

**Comment by lindseydiloreto** [comment]
Looks like a regression was introduced in 4.0.8. I’ll push out a fix for it today.

Thanks for the heads up!

**Comment by lindseydiloreto** [comment]
This has been patched in **v4.0.8.1**. It should be safe once again to update to the latest version. 👍

**Comment by darylknight** [comment]
Looks like it's working now, thank you!

**Comment by cgooderham94** [comment]
Thanks @lindseydiloreto!

**Comment by lindseydiloreto** [comment]
Great, thanks for reporting back @darylknight & @cgooderham94!
