### ISSUE TITLE
Support for Required Address subfields

### ISSUE THREAD

**Issue by lindseydiloreto** [doublesecretagency/craft-googlemaps#3]
Making an Address field "required" is slightly complex. There are up to six normal subfields, plus the coordinates & zoom fields.

So... which subfields must be completed in order to fulfill the requirement?

<img width="656" alt="address@2x" src="https://user-images.githubusercontent.com/5309692/106402129-f50a9b00-63dc-11eb-96d4-016832c3be41.png">

We can assume the Latitude and Longitude subfields (but not Zoom) should be considered "required". This makes sense, but may not truly account for all scenarios. So ideally, we would like to make the required subfields **configurable**.

If all goes according to plan, you will be able to decide which subfields are truly "required". By default, only the Latitude and Longitude will be required.

This feature is expected to be released as early as **v4.1**, or as late as **v4.3**. If anything changes, I'll post back to this thread!

---

> Migrated from Smart Map: https://github.com/doublesecretagency/craft-smartmap/issues/14

**Comment by MoritzLost** [comment]
@lindseydiloreto Required subfields would be a great addition!

> If all goes according to plan, you will be able to decide which subfields are truly "required". By default, only the Latitude and Longitude will be required.

Just to clarify – will it be possible to make latitude & longitude **not** required? This is important for our use-case. We're using an address field to enter an address and/or a geolocation. But not all entries have a geolocation, so some leave the coordinates empty (for example, some entries just have a PO box as their address, so no geolocation that makes sense to display on the map).

Maybe this is already part of the plan, just wanted to point it out in case it isn't :)

**Comment by lindseydiloreto** [comment]
Great news, this is (finally) done! It is now possible to require subfields and/or coordinates in **v4.1.4**.

<img src="https://user-images.githubusercontent.com/5309692/159754064-e04e1bf0-5d28-4d6c-b9b3-bfaff7506ad4.png" width="560">
