### ISSUE TITLE
Ability to specify an open info window on load

### ISSUE THREAD

**Issue by ryguy2407** [doublesecretagency/craft-googlemaps#33]
It would be great if there was an option to set one of the markers as having an open info window on load. I tried running {% do map.openInfoWindow(markerId) %} before rendering the map, but that didn't work.

**Comment by lindseydiloreto** [comment]
Hey there... I'm assuming you closed this because you just updated to the latest version of the Google Maps plugin.

I'm guessing you've already noticed, the `openInfoWindow` method wasn't introduced until **v4.0.11**... which was only released last week on June 18. 🙂

**Comment by ryguy2407** [comment]
Yeah I did just notice it, sorry about that :)
