### ISSUE TITLE
Proximity Search Weirdness

### ISSUE THREAD

**Issue by theskyfloor** [doublesecretagency/craft-googlemaps#36]
Hey!

I am working on a Craft 2 -> 3 upgrade... I switched from SmartMap to Google Maps in the process... which went super well!

Now I am having issues with proximity search... I updated the syntax... what bizarre is that one query works perfectly but all the other ones fail. Mostly I am just wondering how I can best troubleshoot. The logs aren't showing anything. No errors. Etc.

Thanks!

**Comment by lindseydiloreto** [comment]
Hey @theskyfloor, glad to hear the update went smoothly! 🎉 

There's a page in the docs regarding [updating a proximity search](https://plugins.doublesecretagency.com/google-maps/updating-from-smart-map/sorting-entries-by-closest-locations/), but mostly it just says to pay attention to the new & changed [proximity search options](https://plugins.doublesecretagency.com/google-maps/proximity-search/options/).

It's hard to say what your proximity search issue might be... I've got a ton of follow-up questions. Not sure if there's a "right way" to troubleshoot a proximity search. Feel free to hit me up on Discord and we can work through it together in real-time!

**Comment by theskyfloor** [comment]
Will do!
