### ISSUE TITLE
Address in Matrix field doesn't save `raw` or `formatted`

### ISSUE THREAD

**Issue by moayadcodes** [doublesecretagency/craft-googlemaps#43]

**Comment by lindseydiloreto** [comment]
It looks like this is a namespacing issue...

<img width="739" alt="hidden@2x" src="https://user-images.githubusercontent.com/5309692/145941552-08e77ca6-b551-4435-8860-27fcbea816a9.png">

**Comment by lindseydiloreto** [comment]
This is fixed, the patch will be released in **v4.1.1.**
