### ISSUE TITLE
Required subfield settings aren't doing anything

### ISSUE THREAD

**Issue by MoritzLost** [doublesecretagency/craft-googlemaps#47]
I've just updated to the newest plugin version 4.1.5 and I'm trying out the new option to mark some subfields required. The issue I'm having is that the option doesn't seem to have any effect. I have marked several subfields as required, but there's no indicator in the entry form regarding this, and I can save the entry without any validation errors or warnings, even if some or all of the subfields are empty. Not sure if I'm doing something wrong or missing something.

Let me know if you need additional information!

- PHP 8.1.3
- Craft 3.7.37
- Google Maps 4.1.5

**Comment by lindseydiloreto** [comment]
Did you set the field as "Required" within the field layout? That also needs to be enabled.

I could probably stand to clarify that in the docs. Let me know if that was the issue!

**Comment by MoritzLost** [comment]
@lindseydiloreto D'oh, you're right! If I mark the field required in the field layout, the required subfields are validated correctly. Maybe this should be mentioned in the docs somewhere, but it makes sense. My mistake 🤷

**Comment by lindseydiloreto** [comment]
Ok great! I've added a note in the docs, and a similar note on the field's Settings page. Hopefully this helps prevent any future confusion!

<img width="766" alt="required@2x" src="https://user-images.githubusercontent.com/5309692/161099008-cd1bd9e6-010c-488f-9dbe-f6017ffbc0fa.png">
