### ISSUE TITLE
Exception with the `infoWindowTemplate` option for the `map` method in Twig

### ISSUE THREAD

**Issue by MoritzLost** [doublesecretagency/craft-googlemaps#48]
I just tried the update to Google Maps 4.1.5. I have an entry type with a location field, the template for that entry type displays a map with a marker pointing to that location. The marker has an info-window with the address entered into the field.

Here's the Twig code, this was working fine in version 4.1.1:

```twig
{% set map = googleMaps
    .map(location, {
        id: 'offer-institute-single-map',
        infoWindowTemplate: 'maps/marker-info-window',
        mapOptions: {
            fullscreenControl: true,
            gestureHandling: 'cooperative',
            mapTypeControl: false,
            streetViewControl: false,
        },
        styles: get_map_styles(),
    })
    .zoom(location.zoom ?? 13)
%}

{{ map.tag({ assets: false, init: false, }) }}
```

This causes the following exception:

![google-maps-exception](https://user-images.githubusercontent.com/10146880/160842427-62740324-8d73-4762-b502-0b63a477aecc.png)

Looks like a regression caused by the [info window refactoring](https://github.com/doublesecretagency/craft-googlemaps/commit/0284bc0b4f00d8616d48022dd076adb8967c7bb6).

Let me know if you need the full stack trace.

- PHP 8.1.3
- Craft 3.7.37
- Google Maps 4.1.5

**Comment by lindseydiloreto** [comment]
This is now fixed in **v4.1.6**, thanks for reporting it.

@MoritzLost I'll follow up with you via Discord DM to resolve your GDPR concerns.
