### ISSUE TITLE
Craft 4 Compatability timeline?

### ISSUE THREAD

**Issue by myleshyson** [doublesecretagency/craft-googlemaps#50]
Wondering if ya'll have a timeline for a branch/tag that supports Craft 4?

**Comment by lindseydiloreto** [comment]
Funny, I was just planning this out... Hoping to have it all finished by Monday. 🤞

**Comment by lindseydiloreto** [comment]
Happy Monday! A Craft 4 compatible version of the Google Maps plugin has just been released as [**v4.2.0**](https://github.com/doublesecretagency/craft-googlemaps/blob/v4-dev/CHANGELOG.md#changelog).   🎉

**Comment by myleshyson** [comment]
awesome thanks!
