### ISSUE TITLE
"Unable to find marker" when loading map via Sprig

### ISSUE THREAD

**Issue by drifteaur** [doublesecretagency/craft-googlemaps#52]
I followed the guide to set up a dynamic map using Sprig:

https://plugins.doublesecretagency.com/google-maps/guides/sprig/

The map loads fine on the initial page load, and the info windows show when clicking the markers. When the map is refreshed via sprig (in this case, the map is paginated, and going to the next page loads the next set of locations) - the map shows, but the info windows won't open.

On initial load:

<img width="428" alt="initial" src="https://user-images.githubusercontent.com/3732/163341242-86e7edd4-172a-4aca-83da-75824ed394a6.png">

On sprig request:

<img width="428" alt="sprig" src="https://user-images.githubusercontent.com/3732/163341281-9aa47bae-c984-4d6e-ab90-38d645823607.png">

I assume `googleMaps._listInfoWindows` is not being refreshed on a Sprig request somehow. Any way to fix this?

**Comment by drifteaur** [comment]
My Twig code, if it's relevant: 

 ```
{% set mapId = 'properties-map' %}
  {% set mapOptions = {
      'id': mapId,
      'infoWindowTemplate': '_sprig-components/property-filter/_map_bubble',
      'cluster': true,
      'mapOptions': {
          'maxZoom': 17,
      },
      'markerOptions': {
          'icon': '/static/svg/marker.svg',
      }
  } %}
  
  <style>
      #{{mapId}} {
          height: 100%;
      }
  </style>
  
  {{ googleMaps.map(entries, mapOptions).tag() }}
  
  {% if sprig.isRequest %}
      <script>
          googleMaps.init('{{ mapId }}');
      </script>
  {% endif %}
```

**Comment by lindseydiloreto** [comment]
Hi @drifteaur,

There have been some changes recently in that area... which version of the Google Maps plugin are you running?

Also, feel free to DM me on Discord! I can help you get this sorted out in real-time.

**Comment by lindseydiloreto** [comment]
I've done some digging, and you are correct... there is currently a bug when using Sprig alongside of a map with info windows. This bug was introduced recently. And unfortunately, I won't be able to fix it before updating the plugin for Craft 4 compatibility.

As a short term solution, **pin your version of the plugin to `4.1.4` exactly**...

```json
"doublesecretagency/craft-googlemaps": "4.1.4",
```

That should lock you to the last version before this bug was introduced.

Once I've updated the plugin to Craft 4, I'll take another look at resolving this Sprig conflict. Thanks for bringing it up! 👍

**Comment by drifteaur** [comment]
@lindseydiloreto great, the workaround works, thanks :)

**Comment by lindseydiloreto** [comment]
This is fixed in **v4.2.3**.

Go ahead and update when you get a chance, let me know if i missed anything. 👍

**Comment by wesleygooch** [comment]
@lindseydiloreto  Is 4.2.3 still compatible with Craft 3? Thanks for looking into this.

**Comment by lindseydiloreto** [comment]
@wesleygooch It's not, sorry. Since v4.2.0, the plugin requires Craft 4.

**Comment by zizther** [comment]
For anyone looking to support Google Maps 4.2.5+ with Sprig this now requires the `'inline': true` option in plugin, else the data being stored will be added to the bottom of the page which may likely be outside the sprig refreshed content.

```
{{ map.tag({
    'inline': true,
    'assets': false,
    'callback': 'mapReady'
}) }}
```

**Comment by lindseydiloreto** [comment]
Thanks for that note @zizther. 👍 

Fortunately, the [example component](https://github.com/doublesecretagency/craft-googlemaps/blob/056968d95aab33e71bc657ea27973890d57d55aa/docs/examples/twig/_components/proximity-search.twig#L75-L76) already includes `{'inline': true}`. You must have grabbed a copy between February 2022 (when Sprig support was added) and July 2022 (when the `inline` option was added).

To prevent other people from tripping over the same issue, I've [added a note to the documentation...](https://plugins.doublesecretagency.com/google-maps/guides/sprig/#ensure-inline-is-enabled)

**Comment by rhysmatthew** [comment]
@lindseydiloreto I believe I am still getting this error in the latest version of the plugin. 

I've used the proximity search with sprig as a starter. When I update the entries on the map and reinitialize, the info windows are not attached. (`[GM] Unable to find marker "585-address"`) 

It's as if the sprig map still thinks the old entries are present. Although the actual pins are updated correctly. Quite confusing. Any advice would be appreciated, I really wanna use this plugin but it's proving kind of buggy so far with Sprig.

![Screenshot 2023-08-25 at 11 48 08](https://github.com/doublesecretagency/craft-googlemaps/assets/77306946/232552c7-4abe-457b-b7e2-241cbe1705f1)
