### ISSUE TITLE
[Craft 4] Field is immediately marked as changed and a draft is saved on entry load

### ISSUE THREAD

**Issue by Mosnar** [doublesecretagency/craft-googlemaps#59]
When I open an entry with a Google Map field, a new draft is immediately saved and the map field is marked as edited. 

Craft Pro 4.1.4.1
Google Maps 4.2.3

**Comment by lindseydiloreto** [comment]
Sorry for the late reply! I'm sure this behavior is a byproduct of Craft's current draft system.

I'll circle back soon and see if I can iron out this issue. Thanks for reporting it!

**Comment by kylecotter** [comment]
Hi @lindseydiloreto, any update on this one? Experiencing this too with 

Craft Pro 4.3.8.2
Google Maps 4.3.1

Thanks!

**Comment by lindseydiloreto** [comment]
No news, sorry. I haven't quite had a chance to dive in and figure out what's going on. I've noticed that a few other plugins are experiencing the same thing, I might try to figure out what the common thread is.

Thanks for the nudge, I'll try to take a look during the next batch of updates!

**Comment by lindseydiloreto** [comment]
So I dug around for awhile, but couldn't get to the bottom of why this is happening. If you all have any thoughts, please let me know!

Otherwise, it might be a bit longer before I can take another shot at this one.

**Comment by zizther** [comment]
Testing this with Craft 4.3.10 and Google Maps 4.3.3 I don't see this happening opening a new entry or an existing entry.

It does however it does save a draft when any of the address fields have focus.

**Comment by kylecotter** [comment]
Hmm, I'm not seeing any drafts/dirty field indicators now when running Google Maps 4.3.3 and Craft CMS 4.4.1. Curious if y'all see the same.

**Comment by lindseydiloreto** [comment]
Huh, I don't think I can reproduce it anymore either (on Craft 4.4.13). Not sure when it got fixed, but I guess it was an issue in Craft core.

Are you still seeing this issue @Mosnar?

**Comment by zizther** [comment]
@lindseydiloreto Agreed, I am unable to recreate this issue in Craft 4.4.14.

**Comment by lindseydiloreto** [comment]
It looks like this was actually an issue in Craft core, and has since been resolved. Thanks for reporting back! 👍
