### ISSUE TITLE
Add `async`/`defer` to all script tags

### ISSUE THREAD

**Issue by wmdhosting** [doublesecretagency/craft-googlemaps#61]
PLease can you include **async**    to all js tags.. 

Google have sometimes issue..  and it blocks  assets on page or slowdown on page to load.. 
Didnt find any other  way to add .. im on Craft 3. 
(https://plugins.doublesecretagency.com/google-maps/guides/required-js-assets/)

thx

**Comment by lindseydiloreto** [comment]
We are using the `defer` attribute, to ensure that the remote scripts are executed _after_ the page has fully loaded. I'm not an expert, but I do believe that `defer` is preferable to `async` in this scenario.

```html
<script src="https://maps.googleapis.com/maps/api/js?key=[KEY]" defer></script>
<script src="https://unpkg.com/@googlemaps/markerclusterer/dist/index.min.js" defer></script>
<script src="https://yourwebsite.com/cpresources/[HASH]/js/googlemaps.js"></script>
<script src="https://yourwebsite.com/cpresources/[HASH]/js/dynamicmap.js"></script>
```

It's also worth noting that the `async`/`defer` attributes will only take effect on external resources. Therefore it's not necessary to add them to the`<script>` tags of the internal resources.

Please let me know if you think I am mistaken about any of this.

**Comment by lindseydiloreto** [comment]
Upon further research, I may be misinterpreting the term "external"...

<img width="543" alt="The defer attribute is only for external scripts. The defer attribute is ignored if the script tag has no src." src="https://user-images.githubusercontent.com/5309692/180570097-7b7c88de-7181-4a23-9edd-c23895673b51.png">

I now believe that "external" simply means **"not inline"**. And therefore, scripts loaded from your own domain are _also_ considered to be "external".

I can add the `defer` attribute to the other two scripts. Does that sound good to you?

**Comment by wmdhosting** [comment]
Yes :)

Just info, recheked again.. 
And now there is NO:.   **defer**   on any  of these 4  

is that on setting based or auto..

**Comment by lindseydiloreto** [comment]
Good news, I just added this to **v4.2.4**. All four tags now get the `defer` attribute...

```html
<script src="https://maps.googleapis.com/maps/api/js?key=[KEY]" defer></script>
<script src="https://unpkg.com/@googlemaps/markerclusterer/dist/index.min.js" defer></script>
<script src="https://yourwebsite.com/cpresources/[HASH]/js/googlemaps.js" defer></script>
<script src="https://yourwebsite.com/cpresources/[HASH]/js/dynamicmap.js" defer></script>
```

The bad news is, the changes were a bit larger than expected. It's not worth back-porting to Craft 3, unfortunately.

Hopefully you'll be able to update to Craft 4 soon, these changes will be waiting for you when you get there! 🙂
