### ISSUE TITLE
How to manage duplicate coordinates

### ISSUE THREAD

**Issue by vasuhooda** [doublesecretagency/craft-googlemaps#65]
Hello,

What to do when two entries have same coordinate. They are displayed on top of each other and only one is displayed.

**Comment by lindseydiloreto** [comment]
Hi @vasuhooda,

Good question, this is a tricky problem to solve. It's a problem inherent to the Google Maps service itself (and not just the Craft plugin). Here's what I've advised people to do in the past...

---

Assuming you are using [info windows](https://plugins.doublesecretagency.com/google-maps/dynamic-maps/info-windows/), you can have each info window list **all matching locations** for that set of coordinates. So no matter which one is clickable, they will all open the exact same info window, which would then list all matching entries for that location.

Use the **info window Twig template** to perform a lookup of all matching locations...

```twig
{# Filter by subfields matching existing coordinates #}
{% set options = {
    'subfields': {
        'lat': entry.myAddressField.lat,
        'lng': entry.myAddressField.lng
    }
} %}

{# Get all entries with these exact coordinates #}
{% set matchingEntries = craft.entries.myAddressField(options).all() %}

{# Display shared address #}
<div>{{ entry.myAddressField }}</div>
<hr>

{# Loop through businesses (don't override `entry`) #}
{% for business in matchingEntries %}
    <div class="mt-2">
        <div>{{ business.title }}</div>
        <div><a href="{{ business.url }}">More info...</a></div>
    </div>
{% endfor %}
```

There are other ways to approach it as well, but this should cover 90% of use-cases. For more information, check out the docs on how to [Filter by Subfields](https://plugins.doublesecretagency.com/google-maps/guides/filter-by-subfields/).

Hope that helps!

**Comment by lindseydiloreto** [comment]
_Note to self: Add this example to the official docs._

**Comment by lindseydiloreto** [comment]
Finally got a chance to add a proper guide to the docs! 🎉 

https://plugins.doublesecretagency.com/google-maps/guides/locations-with-same-address/
