### ISSUE TITLE
Disable markers for static maps (and only center)

### ISSUE THREAD

**Issue by jimirobaer** [doublesecretagency/craft-googlemaps#66]
Working on a detail page for a real estate agency. We have our own custom (HTML) marker floating above the static map. 

I've tried several things, but it doesn't seem possible to create a map without markers. Static Maps can be generated without markers through the URL by only passing a '_center_' parameter. It does not seem possible to do so using the Twig function `googleMaps.img` however.

Am I missing something, or is this something that is not possible right now?

**Comment by lindseydiloreto** [comment]
Hi Jimi, sorry for the late response. Yes, you definitely can create a static map without markers.

Simply pass an empty array of locations. You must specify both the **center** and **zoom** values for it to work as expected.

```twig
{% set map = googleMaps.img([], {
    'zoom': 11,
    'center': {
        'lat': 34.052235,
        'lng': -118.243683
    }
}) %}
```

Hope that helps!
