### ISSUE TITLE
Minor: Show Map overlaps with field handle

### ISSUE THREAD

**Issue by darylknight** [doublesecretagency/craft-googlemaps#7]
If you have field handles enabled as a developer, it overlaps with the Show Map button:

![image](https://user-images.githubusercontent.com/1250017/109121668-367a3600-7750-11eb-8702-04cbd9e89073.png)

**Comment by lindseydiloreto** [comment]
Thanks for the heads up!

I actually had this working properly at one point, but I think the div IDs must have changed in Craft 3.6. 🙂

**Comment by lindseydiloreto** [comment]
Good news, this is fixed in the recently released **v4.0.1**! &nbsp; 🎉
