### ISSUE TITLE
Can't save plugin settings

### ISSUE THREAD

**Issue by rebkuhn** [doublesecretagency/craft-googlemaps#71]
After installing and activating the plugin, i get the following error when I try to save the server and browser keys on the plugins settings page and the settings are not saved.
```
TypeError
craft\services\Fields::createLayout(): Argument #1 ($config) must be of type array, null given, called in /ath/to/project/vendor/craftcms/cms/src/services/Fields.php on line 1292
```
Craft Version: Craft CMS 4.3.0, Google Maps Plugin Version: 4.2.5 (Testversion), PHP Version: 8.1.12

**Comment by rebkuhn** [comment]
Solved. This was a local problem and not plugin related.

**Comment by lindseydiloreto** [comment]
Ok great, glad you got it sorted! 👍
