### ISSUE TITLE
Address fields missing inside matrix

### ISSUE THREAD

**Issue by philipboomy** [doublesecretagency/craft-googlemaps#74]
When clicking new location in a matrix the address fields are gone. Only way to see them it by trying to save so the validation kicks in and forces the fields to appear.

![Screenshot 2023-02-05 at 20 06 57](https://user-images.githubusercontent.com/29286831/216839644-51bbf958-2a5c-47cc-a0f9-954b95b5b328.jpg)
![Screenshot 2023-02-05 at 20 08 16](https://user-images.githubusercontent.com/29286831/216839665-bf3253b4-3f72-43b7-9ec6-9bbf15af5cd0.jpg)

Craft 4.3.7
Google Maps version 4.3.0

**Comment by lindseydiloreto** [comment]
Hi @philipboomy, thanks for reporting this. I'll take a look and try to get it fixed. 🙏

**Comment by lindseydiloreto** [comment]
This has been fixed in **v4.3.3**. Thanks again for reporting it! 👍
