### ISSUE TITLE
Using Google Maps plugin multiple times in Matrix

### ISSUE THREAD

**Issue by phillipsandoveracademy** [doublesecretagency/craft-googlemaps#80]
We are running Google Maps 4.3.3 and Craft CMS 4.3.11 on local dev. On our site, we currently have a matrix field that uses the Google Maps plugin twice. One use to set the front-end map center and zoom level (mapCenterZoom field) and one use to create map pins (mapPin field).

![screenshot-andover4 ddev site-2023 03 09-15_58_07](https://user-images.githubusercontent.com/11964584/224173045-f4a798dd-d7d2-4c07-b8da-dddb21fad254.png)

On the Matrix -> Super Table -> Matrix (pins field), we get a JS error, which appears to block the loading of the field details for the mapPin field.

![Screen Shot 2023-03-09 at 5 08 47 PM](https://user-images.githubusercontent.com/11964584/224174257-499236ea-6dda-4da1-853b-1835a2c1f0c5.png)

Let me know if you need to know anything else about our setup. Thanks!

**Comment by lindseydiloreto** [comment]
Just wanted to leave a quick update...

Within a few days of your initial post, I was able to partially fix this issue. That fix, unfortunately, revealed another similar issue which also needs to be addressed. After partially fixing the issue, I was pulled away to fix an urgent client issue.

I'm hoping to circle back soon and finish resolving this one!

**Comment by lindseydiloreto** [comment]
I believe this is fixed, sorry for the delay!

When you get a chance, please update to [v4.3.4](https://github.com/doublesecretagency/craft-googlemaps/releases/tag/4.3.4) and let me know if that does the trick. 🤞
