### ISSUE TITLE
Multiple markers on the same location

### ISSUE THREAD

**Issue by splendidrob** [doublesecretagency/craft-googlemaps#81]
Do you have any suggestions as to how to handle multiple markers on the same location? We have a site that displays a map with many entries showing on the exact same location (a University for example). Unfortunately the front end map just shows the top marker and it is impossible to access any of the others below. Is there a good solution to space these out in a cluster or similar without having to go through every single entry and slightly offset the location? When zoomed out the markers show as a cluster which works well but when zooming in to select an individual item you then only have access to one. You can view the issue here: https://bridginghistories.com/what-you-have-shared

**Comment by lindseydiloreto** [comment]
Hi @splendidrob, this can totally be done, but it's a tricky problem to solve...

- https://github.com/doublesecretagency/craft-googlemaps/issues/65#issuecomment-1267471201

I'm going to re-open that other thread, as a reminder to add that code example to the official documentation. 👍

**Comment by splendidrob** [comment]
Ah perfect! Sorry I missed that thread...will give it a try. Much appreciated!

**Comment by lindseydiloreto** [comment]
Better late than never... I've written up an official "how to" guide for folks in this situation:

https://plugins.doublesecretagency.com/google-maps/guides/locations-with-same-address/
