### ISSUE TITLE
Marker Cluster Zoom Issue

### ISSUE THREAD

**Issue by brihermanson** [doublesecretagency/craft-googlemaps#83]
This plugin is so great, but I'm having one issue. When clicking on a marker cluster, there is a momentary flash of a overly zoomed in version of the map before the correct zoom level load in. Is there a way to prevent this?

Here is what shows momentarily on clicking a cluster: 
<img width="1565" alt="Screen Shot 2023-05-08 at 8 53 47 AM" src="https://user-images.githubusercontent.com/99825025/236831364-2a9ebc72-df3a-47ed-957d-6aba451b5486.png">

Here is the correct zoom level it settles into after a split second: 
<img width="1570" alt="Screen Shot 2023-05-08 at 8 54 18 AM" src="https://user-images.githubusercontent.com/99825025/236831403-990f22f2-1c73-4baa-a59d-18f25b6694b4.png">

Any ideas? Thank you!

**Comment by lindseydiloreto** [comment]
Hi @brihermanson, glad you're digging the plugin! 🙏 

There's nothing that can be done about that, unfortunately. It's purely an artifact of the [Marker Clusterer library](https://github.com/googlemaps/js-markerclusterer), which is now maintained by Google directly. Only Google could solve that problem, but I doubt it's high on their radar.

For better or worse, it has nothing to do with the Craft plugin... you would be seeing the same behavior whether you used the plugin or not. I know it's not the answer you're looking for, but take solace in the fact that it's not affecting only you.

Hope that helps!
