### ISSUE TITLE
Support for older browsers in JS

### ISSUE THREAD

**Issue by zizther** [doublesecretagency/craft-googlemaps#85]
There are still some users who have devices not on iOS v14+ which supports nullish coalescing operators which are being used in the plugin JS.
Would it be possible to support these?

For example dynamicmap.js Line 1310:
`this._cluster.algorithm ?? null`

**Comment by lindseydiloreto** [comment]
Thanks for reporting! This is now fixed on the `v4-dev` branch.

To test it out before the next release, change the plugin version specified in `composer.json`...

```js
"doublesecretagency/craft-googlemaps": "dev-v4-dev"
```

Then run `composer update`.

Let me know if that does the trick!

**Comment by lindseydiloreto** [comment]
This fix has been officially released in [4.3.5](https://github.com/doublesecretagency/craft-googlemaps/releases/tag/4.3.5). 👍

**Comment by zizther** [comment]
Thanks for supporting this one.
