### ISSUE TITLE
Slow loading with many entries

### ISSUE THREAD

**Issue by splendidrob** [doublesecretagency/craft-googlemaps#88]
Just wandering what the best options are when dealing with many entries being used for map markers? I have a few hundred and the page load is getting very slow, the main entries on my page are paginated but obviously that doesn't work with the map markers...any suggestions appreciated!

**Comment by lindseydiloreto** [comment]
Sounds like you need to do a bit of caching! You have many caching options, including the native `{% cache %}` tag.

If caching messes up how the map loads, check out the guides on [Required JS Assets](https://plugins.doublesecretagency.com/google-maps/guides/required-js-assets/) and/or [Delaying Map Initialization](https://plugins.doublesecretagency.com/google-maps/guides/delay-map-init/).

Hope that helps!
