### ISSUE TITLE
Proximity Search Weirdness

### ISSUE THREAD

**Issue by brettburwell** [doublesecretagency/craft-googlemaps#89]
Hi there Lindsey. I hope all's well on that end. Reaching out hoping you can help me with a bit of a mystery issue that popped up. 

We have a [site that's been happily using the Google Maps plugin](https://omegayeast.com/buy/in-store)—and specifically the proximity search feature—for many years now. Just today the client reported that the proximity search wasn't working as expected, with the vast majority of searches returning no results (when we know there are definitely entries within the defined range and location). 

After taking a good long look and reading and re-reading the docs, I'm drawing a blank about what might be happening. 

Here's what I've done to trouble shoot: 
- Double checked the [element query syntax and query params](https://plugins.doublesecretagency.com/google-maps/proximity-search/#query-parameters) we're using.
- Tested using hard coded params. 
- Double checked the API key and restriction settings.
- Updated to the latest Craft 3 version of the plugin (4.1.9).
- Tested the address field in a new entry (and confirmed that the address lookup was working as expected).

None of that turned up anything helpful. 

**But**, when I increased the `range` to 1000 miles I was able to get results to return (just not expected or logical ones). The odd thing is, I can see in the dev tools console that Google Maps is using a lat and longitude based somewhere in New York (which makes sense based on the map centering). But if I do a proximity search with `New York` as the `target` and `range` set to `1000`, the same results are returned and the distance is the same as if I use `Chicago`. 

It made me wonder if somehow the geolocation data associated with the entries got lost somewhere along the way. So I tried bulk resaving all of the entries in that section, but didn't have any luck with that either. 

Something funky is happening, I'm just not sure what it is. I hate to even reach out, because I know these types of issues are the worst to track down, but I'm hoping you might be able to get me pointed in the right direction. Any info or assistance you can pass along would be much appreciated. 

If there's any additional info that'd be helpful for me to share let me know. Thanks in advance.

**Comment by lindseydiloreto** [comment]
Hey @brettburwell, hope everything is well with you! Sorry for the insanely late reply, you caught me while I was travelling a lot this summer. 😅

If you're still running into this, ping me on Discord (@lindseydiloreto). We can troubleshoot it together in real-time, and try to get to the bottom of it.

Assuming we uncover something interesting, we can circle back and add it to this thread. 👍

**Comment by brettburwell** [comment]
Hey hey. Thanks for the reply @lindseydiloreto. 

I'm a bugger. I should have circled back to close this issue, but it got lost in the mix. 

Turns out the issue was with the Google API keys themselves. Cycling the keys and regenerating a fresh set resolved the issue. As best as I could tell, the settings of the new keys were exactly the same as the old keys, so I'm still not sure what happened. But I'll take the win and move on! 

Hope you had a good summer and some fun travels.

**Comment by lindseydiloreto** [comment]
Ok awesome, glad you got everything sorted out. Thanks for reporting back! 👍
