### ISSUE TITLE
Dynamic JS Method missing panBy

### ISSUE THREAD

**Issue by sander-lameco** [doublesecretagency/craft-googlemaps#93]
I would like the use [panBy](https://developers.google.com/maps/documentation/javascript/reference/map#Map.panBy) but it seems to be missing in the Dynamic Maps JS.

The reason being is that we have something overlapping the Google Map and would like to offset the map a bit to counter this overlap.

**Comment by lindseydiloreto** [comment]
Hi @sander-lameco, sorry for the late reply.

Good news, you can access the underlying Google Maps API object at any time!

```js
// Internally used Google API object
map._map
```

Meaning that you should be able to do something like this...

```js
// Get the plugin's map object
const map = googleMaps.getMap(mapId);

// Pan using Google's map object
map._map.panBy(x, y);
```

Hope that helps!

**Comment by sander-lameco** [comment]
@lindseydiloreto thanks for the tip, but how do I check if `googleMaps` is available?.
When trying your code I (of course) get `googleMaps is not defined`.
I can't find anything in the docs related to this.

**Comment by lindseydiloreto** [comment]
If `googleMaps` is not defined, it means some dynamic JS is trying to run before the plugin's JavaScript files have been properly loaded.

The docs for [Required JS Assets](https://plugins.doublesecretagency.com/google-maps/guides/required-js-assets/) describe why those files are important, and how they can be automatically or manually loaded.
