### ISSUE TITLE
lat and long not saved in the backend

### ISSUE THREAD

**Issue by paolocoppo** [doublesecretagency/craft-googlemaps#96]
Craft CMS Pro 4.5.3
Google Maps 4.3.5

Other active plugins:
- Redactor 3.0.4
- Super Table 3.0.9

Active Google APIs:
- Maps JavaScript API
- Maps Static API
- Geocoding API
- Places API

Google API keys (2x) are set and added to the plugin (via env vars)
For now, the two keys have no restrictions.
From the plugin: Test the Google API keys -> both keys are valid

In the backend, when I save an entry that has the Address field, the lat and long are not saved.
No js errors in the browser console.
Checking console.cloud.google.com shows that there are calls to:
- Maps JavaScript API
- Geocoding API
- Places API 
All calls are good, zero failed ones.

Any idea about was is wrong?
TIA

**Comment by lindseydiloreto** [comment]
Hi @paolocoppo,

This is a tough one to diagnose, everything you are describing sounds correct. I can't recall a case where _only latitude and longitude_ were being omitted from the resulting data.

Would you mind pinging me on Discord (@lindseydiloreto) when you get a chance? We can troubleshoot it together to figure out what the issue is, and report our findings back on this thread.

**Comment by paolocoppo** [comment]
Hi @lindseydiloreto, 
this is now solved and it was a _user_ mistake, more or less.

I have used this plugin with a few Craft 3 installs, and it always works. 
Note that in Craft3, in  Address field -> Subfield Manager -> Street Address I had the "Auto" checkbox unchecked. And all works.

In craft 4, that checkbox MUST be checked, then all will work.

Not sure if there is a bug in either version, but at least I can have the plugin fully working in both craft versions.

**Comment by paolocoppo** [comment]
closing as it's resolved

**Comment by lindseydiloreto** [comment]
Ok great, glad you got that resolved! Sounds like it might have been an edge-case bug in the Craft 3 version.

Since it's a relatively minor bug and Craft 3 is nearing EOL, we probably won't bother fixing it. But regardless, thanks for the full explanation! 🙂
