### ISSUE TITLE
Recommended way to access lookup method from a custom module?

### ISSUE THREAD

**Issue by twosixcode** [doublesecretagency/craft-googlemaps#97]
Hi, been using this plugin for a long time on several projects. Great work. This is not an issue, but a question, just wasn't sure where to post it for good visibility. 

I have a need to use the `lookup` method of the plugin to geocode some addresses. These are addresses coming into Craft automatically, and I'm planning to geocode them as a queued job. In case that matters.

Is there a recommended way to access the `lookup` method of the Google Maps plugin from my custom module? I'm flailing a bit and I saw that there was no service for this in the plugin itself, which is what I was hoping to see. Is there another way to accomplish this?

Thanks for any example code or recommendations you can provide!

PS this project is still on Craft v3 and is using v4.1 of the Maps plugin. We're about to update, but need to accomplish this work first. So any advice you have is greatly appreciated.

**Comment by twosixcode** [comment]
I figured it out

```
use doublesecretagency\googlemaps\helpers\GoogleMaps;

$coords = GoogleMaps::lookup($address)->coords();
```

**Comment by lindseydiloreto** [comment]
Ok awesome, that's exactly right! Glad you got it sorted out. 👍
