### ISSUE TITLE
Minifying the googlemaps.js and dynamicmap.js on cpresources

### ISSUE THREAD

**Issue by sander-lameco** [doublesecretagency/craft-googlemaps#98]
Since the files are loaded in the frontend, would it be possible to minify these files?
Or is it something we misconfigured?
We're asking since Lighthouse and SEranking are giving off warnings as the files are not minified.

**Comment by lindseydiloreto** [comment]
Thanks for the feature request! I've considered this before... my thought has been to leave it unminified to make the methods more discoverable.

However, there is a fair case for minifying them as well. I'll see if I can provide an option to load minified versions of those files.

Not sure what the ETA is, but I'll post any updates back on this thread.

**Comment by sander-lameco** [comment]
Thanks @lindseydiloreto , no problem, there is no real pressure behind this as it is only a warning but would be nice to be able to minify it in the (near) future.

**Comment by lindseydiloreto** [comment]
Great news, this is done! Now available in [v4.3.7](https://github.com/doublesecretagency/craft-googlemaps/releases/tag/4.3.7) 👍 

If using a PHP config file, there is now an additional setting to [`minifyJsFiles`](https://plugins.doublesecretagency.com/google-maps/getting-started/config/#minifyjsfiles). Enabling this will serve up the minified versions of those front-end files.
