### ISSUE TITLE
Search based on region defined as a set of coordinates

### ISSUE THREAD

**Issue by aloco** [doublesecretagency/craft-googlemaps#99]
Hi, 

not sure if I overlooked this in the docs, but is it possible to query for entries with specific coordinates based on a set of coordinates which defines a region? Like a district in a city? "Show me all entries within the district"

thanks in advance

**Comment by lindseydiloreto** [comment]
Hi @aloco,

You can [Filter by Subfields](https://plugins.doublesecretagency.com/google-maps/guides/filter-by-subfields/) to get only the locations which match a specific subfield.

Sounds like you're looking for something like this...

```twig
{% set options = {
    'subfields': {
        'city': 'New York'
    }
} %}
```
... or perhaps this...
```twig
{% set options = {
    'subfields': {
        'county': 'Queens County'
    }
} %}
```

Hope that helps!
